import {
  boolean,
  date,
  doublePrecision,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  smallint,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { user } from "./auth-schema";

/**
 * Application tables. Kept separate from auth-schema.ts because that file is
 * regenerated by `npm run auth:generate` and would clobber anything added to it.
 *
 * Note every foreign key to a person is `text`, not `uuid` — Better Auth's
 * `user.id` is a text column.
 */

export const applicationStage = pgEnum("application_stage", [
  "draft",
  "submitted",
  "r1_queued",
  "r1_done",
  "r2_queued",
  "r2_done",
  "decided",
]);

export const decisionKind = pgEnum("decision_kind", [
  "accepted",
  "waitlisted",
  "rejected",
]);

export const rsvpState = pgEnum("rsvp_state", [
  "pending",
  "confirmed",
  "declined",
  "expired",
]);

export const application = pgTable(
  "application",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),

    // ── the form ──────────────────────────────────────────────────────────
    // Free-form answers live in jsonb; facts we filter, group or report on get
    // promoted to real columns below. Last year everything was free text and
    // the data was unusable — "Stanford" vs "Stanford University" can't be
    // counted, and "hackathons attended" had a maximum of 10,000.
    answers: jsonb("answers").notNull().default({}),
    formVersion: integer("form_version").notNull().default(1),

    // ── promoted facts ────────────────────────────────────────────────────
    firstName: text("first_name"),
    lastName: text("last_name"),
    // Age is evaluated against the event's first day, not submission date, so
    // someone who turns 18 in October is eligible for a November event.
    dateOfBirth: date("date_of_birth"),
    schoolName: text("school_name"),
    schoolCountry: text("school_country"),
    schoolRegion: text("school_region"),
    gradYear: smallint("grad_year"),
    // Bucketed on the form (0 / 1-2 / 3-5 / 6+) rather than a free integer.
    hackathonsBucket: text("hackathons_bucket"),
    firstHackathon: boolean("first_hackathon"),
    // Times at Immerse the Bay before (0 / 1 / 2 / 3+). Year-over-year
    // repeat-attendee metric, never an admissions signal.
    priorAttendance: text("prior_attendance"),
    primarySkill: text("primary_skill"),
    portfolioUrl: text("portfolio_url"),
    tshirtSize: text("tshirt_size"),
    dietaryNeeds: text("dietary_needs"),
    accessibilityNeeds: text("accessibility_needs"),

    resumeUrl: text("resume_url"),
    // Separate, unchecked opt-in. Never a condition of acceptance — filter on
    // this before any sponsor export.
    sponsorShareOk: boolean("sponsor_share_ok").notNull().default(false),

    // Self-reported, as a cross-check on the UTM data below. Catches
    // word-of-mouth, which no amount of tracking can see.
    heardAboutUs: text("heard_about_us"),
    // Optional name-drop when heard via a friend, class, or partner club:
    // tells us which individual people drive signups.
    heardAboutUsName: text("heard_about_us_name"),

    // ── referrals ─────────────────────────────────────────────────────────
    // Minted on first submit. A referred application carries
    // utm_source='ref' + utm_content=<code>; only completed (submitted)
    // applications count toward the leaderboard.
    referralCode: text("referral_code").unique(),
    referralAnonymous: boolean("referral_anonymous").notNull().default(false),

    // ── first-touch attribution ───────────────────────────────────────────
    // Copied off the itb_attr cookie at submit. Explicit columns rather than
    // jsonb so `GROUP BY utm_source` stays trivial.
    utmSource: text("utm_source"),
    utmMedium: text("utm_medium"),
    utmCampaign: text("utm_campaign"),
    utmContent: text("utm_content"),
    utmTerm: text("utm_term"),
    referrer: text("referrer"),
    landingPath: text("landing_path"),
    firstTouchAt: timestamp("first_touch_at", { withTimezone: true }),

    // ── review pipeline ───────────────────────────────────────────────────
    // Present from day one even though reviewing ships weeks later: these cost
    // nothing empty, and `queue_seed` in particular must be assigned at insert
    // so the review queue is randomly ordered rather than submission-ordered.
    stage: applicationStage("stage").notNull().default("draft"),
    queueSeed: doublePrecision("queue_seed")
      .notNull()
      .default(sql`random()`),
    targetReviews: smallint("target_reviews").notNull().default(2),
    // Denormalised: open claims + valid reviews. Maintained by trigger, because
    // `SELECT ... FOR UPDATE` cannot be combined with an aggregate.
    coverage: smallint("coverage").notNull().default(0),
    r1Score: numeric("r1_score", { precision: 6, scale: 3 }),
    r1Spread: numeric("r1_spread", { precision: 6, scale: 3 }),
    r1Rank: integer("r1_rank"),

    // ── decision ──────────────────────────────────────────────────────────
    decision: decisionKind("decision"),
    decidedAt: timestamp("decided_at", { withTimezone: true }),
    decisionNote: text("decision_note"),

    rsvp: rsvpState("rsvp"),
    rsvpDeadline: timestamp("rsvp_deadline", { withTimezone: true }),
    rsvpAt: timestamp("rsvp_at", { withTimezone: true }),
    checkedInAt: timestamp("checked_in_at", { withTimezone: true }),

    submittedAt: timestamp("submitted_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    // One application per person.
    uniqueIndex("application_user_unique").on(t.userId),
    index("application_stage_idx").on(t.stage, t.submittedAt),
    // Answers the question the org actually asks: which source produced the
    // most applicants, and which produced the most *accepted* ones.
    index("application_attribution_idx").on(t.utmSource, t.utmMedium),
    index("application_decision_idx").on(t.decision, t.rsvp),
  ],
);

/**
 * Attribution captured at signup, before an application row exists.
 *
 * A separate table rather than columns on `user` so that regenerating the auth
 * schema can't drop it. Without this you can't tell "Instagram sends 400 signups
 * who never finish" from "a partner club sends 40 who all submit" — opposite
 * marketing conclusions from the same submitted-application data.
 */
export const userAttribution = pgTable("user_attribution", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  utmSource: text("utm_source"),
  utmMedium: text("utm_medium"),
  utmCampaign: text("utm_campaign"),
  utmContent: text("utm_content"),
  utmTerm: text("utm_term"),
  referrer: text("referrer"),
  landingPath: text("landing_path"),
  firstTouchAt: timestamp("first_touch_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/**
 * Short-link clicks for printed QR codes and campaign links.
 *
 * Self-hosted rather than Dub or Bitly: Dub's free tier is ~1,000 tracked events
 * (one busy afternoon at an activities fair) and Bitly's free plan now shows an
 * interstitial ad before redirecting — not something to put between a flyer scan
 * and an application form.
 */
export const linkClick = pgTable(
  "link_click",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    code: text("code").notNull(),
    referrer: text("referrer"),
    userAgent: text("user_agent"),
    at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("link_click_code_idx").on(t.code, t.at)],
);

/** Stress-test and general feedback, written from /feedback. */
export const feedback = pgTable("feedback", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id").references(() => user.id, { onDelete: "set null" }),
  deviceMethod: text("device_method"),
  broke: text("broke"),
  friction: text("friction"),
  formNotes: text("form_notes"),
  duration: text("duration"),
  mobileNotes: text("mobile_notes"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/**
 * Admin-defined tags, applied to applications from the admin console.
 * Archived tags keep their assignments (history stays intact) but stop
 * appearing in pickers.
 */
export const tag = pgTable("tag", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull().unique(),
  archived: boolean("archived").notNull().default(false),
  createdBy: text("created_by").references(() => user.id, {
    onDelete: "set null",
  }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const applicationTag = pgTable(
  "application_tag",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    applicationId: uuid("application_id")
      .notNull()
      .references(() => application.id, { onDelete: "cascade" }),
    tagId: uuid("tag_id")
      .notNull()
      .references(() => tag.id, { onDelete: "cascade" }),
    addedBy: text("added_by").references(() => user.id, {
      onDelete: "set null",
    }),
    at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("application_tag_unique").on(t.applicationId, t.tagId),
    index("application_tag_tag_idx").on(t.tagId),
  ],
);

/**
 * Append-only audit trail. Backs the "admins can monitor every account"
 * requirement, and records PII reveals during non-blind round-two review.
 */
export const applicationEvent = pgTable(
  "application_event",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    applicationId: uuid("application_id").references(() => application.id, {
      onDelete: "cascade",
    }),
    actorId: text("actor_id").references(() => user.id, {
      onDelete: "set null",
    }),
    actorKind: text("actor_kind").notNull(), // applicant | reviewer | admin | system
    kind: text("kind").notNull(),
    payload: jsonb("payload").notNull().default({}),
    at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("application_event_app_idx").on(t.applicationId, t.at),
    index("application_event_kind_idx").on(t.kind, t.at),
  ],
);
