/**
 * Single import point for the Drizzle schema.
 *
 * `auth-schema.ts` is generated by `npm run auth:generate` — don't hand-edit it.
 * `app-schema.ts` is ours.
 */
export * from "./auth-schema";
export * from "./app-schema";
